apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.argocd.name }}
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: kong-ai-gateway-platform
    {{- range $k, $v := .Values.namespaces.argocd.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
