image:
  repository: docker.io/uttamgiri/kong-ai-gateway
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
  adminPort: 8001

istio:
  enabled: false
  gateway:
    selector:
      istio: ingressgateway
    hosts:
      - kong-ai-gateway.example.internal
    port: 80
