image:
  repository: docker.io/uttamgiri32/kong-ai-gateway
  tag: "0.1.2"
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    memory: 1Gi

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
  adminPort: 8001
  managerPort: 8002

istio:
  enabled: true
  # NLB hostname from: kubectl -n istio-ingress get svc istio-ingressgateway
  publicHost: ad03799c62bed4c97bb86fa9e9620e21-4fe42c6b263ea65a.elb.us-east-2.amazonaws.com
  gateway:
    selector:
      istio: ingressgateway
    hosts:
      - "*"
    port: 80
